// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: spot_instrument_service_messages.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_instrument_service_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_messages_proto_rawDescGZIP(), []int{0}
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_instrument_service_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_messages_proto_rawDescGZIP(), []int{1}
}

var File_spot_instrument_service_messages_proto protoreflect.FileDescriptor

const file_spot_instrument_service_messages_proto_rawDesc = "" +
	"\n" +
	"&spot_instrument_service_messages.proto\x12\x1aspot_instrument_service_v1\"\x14\n" +
	"\x12ViewMarketsRequest\"\x15\n" +
	"\x13ViewMarketsResponseB#Z!github.com/ewik2k21/grpc-hard/pkgb\x06proto3"

var (
	file_spot_instrument_service_messages_proto_rawDescOnce sync.Once
	file_spot_instrument_service_messages_proto_rawDescData []byte
)

func file_spot_instrument_service_messages_proto_rawDescGZIP() []byte {
	file_spot_instrument_service_messages_proto_rawDescOnce.Do(func() {
		file_spot_instrument_service_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_instrument_service_messages_proto_rawDesc), len(file_spot_instrument_service_messages_proto_rawDesc)))
	})
	return file_spot_instrument_service_messages_proto_rawDescData
}

var file_spot_instrument_service_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spot_instrument_service_messages_proto_goTypes = []any{
	(*ViewMarketsRequest)(nil),  // 0: spot_instrument_service_v1.ViewMarketsRequest
	(*ViewMarketsResponse)(nil), // 1: spot_instrument_service_v1.ViewMarketsResponse
}
var file_spot_instrument_service_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spot_instrument_service_messages_proto_init() }
func file_spot_instrument_service_messages_proto_init() {
	if File_spot_instrument_service_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_instrument_service_messages_proto_rawDesc), len(file_spot_instrument_service_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spot_instrument_service_messages_proto_goTypes,
		DependencyIndexes: file_spot_instrument_service_messages_proto_depIdxs,
		MessageInfos:      file_spot_instrument_service_messages_proto_msgTypes,
	}.Build()
	File_spot_instrument_service_messages_proto = out.File
	file_spot_instrument_service_messages_proto_goTypes = nil
	file_spot_instrument_service_messages_proto_depIdxs = nil
}
